## About the dataset
#### Currently we have dataset of commodities that change the Geopolitical Equation of Each Country and we can measure the impact of it. By observing transaction of commodities between the countries we can forecast superpower and their decission which impact the price Globally of Gold, Bitcoin, Crude and Petroleum Oil.<br>

We have the dataset of each commodities and we will preprocess each dataset to get clean dataset so we can forecast each their decision and upcomming events.

#### Structure of our raw data as follows -

- **1** Bitcoin <br>
- **2** Crude and Petroleum Oils <br>
    - **2.1** Export - Crude Oil <br>
    - **2.2** Import - Crude Oil <br>
        - **2.2.1** 2019 <br>
        - **2.2.2** 2020 <br>
        - **2.2.3** 2021 <br> 
        - **2.2.4** 2022 <br>
        - **2.2.5** 2023 <br>
        - **2.2.6** 2024 <br>
- **3** Gold <br>
    - **3.1** Export - Crude Oil <br>
    - **3.2** Import - Crude Oil <br>
        - **3.3.1** 2019 <br>
        - **3.3.2** 2020 <br>
        - **3.3.3** 2021 <br> 
        - **3.3.4** 2022 <br>
        - **3.3.5** 2023 <br>
        - **3.3.6** 2024 <br>  
- **4** Price and Micro Time Series<br>

### Importing Libraries for preprocessing

In [216]:
import pandas as pd
import numpy as np

## Bitcoin Preprocessing

In [217]:
# reading data
btc = pd.read_csv('Raw/BITCOINITY/bitcoinity_data.csv')
btc.head(10)

,Time,bitstamp,cex.io,coinbase,exmo,kraken,paymium
0,2025-06-02 00:00:00 UTC,63.676077,NaN,75.264516,9.823327,65.772330,0.051803
1,2025-06-09 00:00:00 UTC,1017.704045,NaN,1479.039509,73.279674,994.456062,7.180464
2,2025-06-16 00:00:00 UTC,998.468447,0.000470,1641.574995,73.220186,1217.290954,8.780651
3,2025-06-23 00:00:00 UTC,922.483559,NaN,1250.520250,73.396869,1014.335795,5.225518
4,2025-06-30 00:00:00 UTC,679.815773,NaN,1187.202267,73.219486,871.376800,9.966818
5,2025-07-07 00:00:00 UTC,1247.303819,3.644631,2096.984609,74.168432,1663.437297,16.539740
6,2025-07-14 00:00:00 UTC,1187.769976,1.560906,1989.949330,74.809865,1243.062676,15.689782
7,2025-07-21 00:00:00 UTC,967.290493,0.830292,1341.123694,74.115077,885.566971,11.777674
8,2025-07-28 00:00:00 UTC,1050.080841,2.906849,1531.636641,73.688576,1099.042596,11.321207
9,2025-08-04 00:00:00 UTC,1030.717401,2.677607,1016.079490,73.962259,813.465248,12.798302

In [218]:
# shape of the dataset
btc.shape

(27, 7)

In [219]:
# information about the dataset
btc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Time      27 non-null     object
 1   bitstamp  27 non-null     float64
 2   cex.io    15 non-null     float64
 3   coinbase  13 non-null     float64
 4   exmo      27 non-null     float64
 5   kraken    27 non-null     float64
 6   paymium   27 non-null     float64
dtypes: float64(6), object(1)
memory usage: 1.6+ KB

The data is imbalance and time parameter in object so we will convert it into timeseries with dd/mm/yyyy. Furthermore their is NaN values in our dataset that we will process and remove it.

In [220]:
btc.describe()

          bitstamp     cex.io     coinbase        exmo       kraken    paymium
count    27.000000  15.000000    13.000000   27.000000    27.000000  27.000000
mean   1177.129391   1.767630  1289.266440   98.112607  1354.857246  11.680512
std     504.497949   1.733282   602.028870   50.004521   618.309409   4.454373
min      63.676077   0.000470    75.264516    9.823327    65.772330   0.051803
25%     972.967148   0.003700  1187.202267   73.249930  1016.301624   8.947464
50%    1119.286706   1.827838  1445.834897   74.168432  1217.290954  12.316254
75%    1414.947678   2.792228  1566.125220  141.170919  1658.254207  13.784398
max    2627.101060   6.040993  2096.984609  191.925622  3166.813746  21.510629

In [221]:
# Number of missing value available in dataset
btc.isna().sum()

Time         0
bitstamp     0
cex.io      12
coinbase    14
exmo         0
kraken       0
paymium      0
dtype: int64

In [222]:
#dropping dubplicates from dataset
btc.drop_duplicates(inplace=True)
btc.head()

,Time,bitstamp,cex.io,coinbase,exmo,kraken,paymium
0,2025-06-02 00:00:00 UTC,63.676077,NaN,75.264516,9.823327,65.772330,0.051803
1,2025-06-09 00:00:00 UTC,1017.704045,NaN,1479.039509,73.279674,994.456062,7.180464
2,2025-06-16 00:00:00 UTC,998.468447,0.00047,1641.574995,73.220186,1217.290954,8.780651
3,2025-06-23 00:00:00 UTC,922.483559,NaN,1250.520250,73.396869,1014.335795,5.225518
4,2025-06-30 00:00:00 UTC,679.815773,NaN,1187.202267,73.219486,871.376800,9.966818

In [223]:
#Handle Missing Values
btc_numeric = btc.select_dtypes(include='number').columns
btc[btc_numeric] = btc[btc_numeric].fillna(btc[btc_numeric].median())

In [224]:
# the following time column have function in it so we need to change it first and then we will change the type to datetime.
type(btc['Time'].iloc[0])

str

In [225]:
# converting data type
btc['Time'] = pd.to_datetime(
    btc['Time'],
    format='%Y-%m-%d %H:%M:%S %Z',
    utc=True,
    errors='coerce'
)
btc['Time'] = pd.to_datetime(btc["Time"].dt.strftime('%Y-%m-%d'))
btc.head()

,Time,bitstamp,cex.io,coinbase,exmo,kraken,paymium
0,2025-06-02,63.676077,1.827838,75.264516,9.823327,65.772330,0.051803
1,2025-06-09,1017.704045,1.827838,1479.039509,73.279674,994.456062,7.180464
2,2025-06-16,998.468447,0.000470,1641.574995,73.220186,1217.290954,8.780651
3,2025-06-23,922.483559,1.827838,1250.520250,73.396869,1014.335795,5.225518
4,2025-06-30,679.815773,1.827838,1187.202267,73.219486,871.376800,9.966818

In [226]:
# Saving the bitcoin data into interim
interim_path = '../data/interim/bitcoinity_cleaned.csv'
btc.to_csv(interim_path, index=False)

## Crude Petroleum Oils

### Import

In [227]:
# reading crude oil import dataset 
cpo_im = pd.read_excel(r'Raw\crude petroleum oils\Crude oil Import\TradeData.xlsx')

In [228]:
# printing first 5 rows from dataset
cpo_im.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20190101,2019,52,2019,4,AFG,Afghanistan,M,...,1.188788e+08,False,0.0,False,3.437247e+07,0.0,3.437247e+07,0,False,True
1,C,A,20190101,2019,52,2019,20,AND,Andorra,M,...,3.236850e+03,False,0.0,False,1.207124e+04,NaN,1.207124e+04,0,False,True
2,C,A,20190101,2019,52,2019,24,AGO,Angola,M,...,1.804062e+03,False,0.0,False,1.761858e+04,NaN,1.761858e+04,0,False,True
3,C,A,20190101,2019,52,2019,28,ATG,Antigua and Barbuda,M,...,1.356000e+02,False,0.0,False,5.807370e+02,NaN,5.807370e+02,0,False,True
4,C,A,20190101,2019,52,2019,31,AZE,Azerbaijan,M,...,NaN,False,0.0,False,1.913474e+08,NaN,1.913474e+08,0,False,True

In [229]:
#shape of the dataset
cpo_im.shape

(745, 47)

In [230]:
#information about the dataset
cpo_im.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 745 entries, 0 to 744
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   typeCode                  745 non-null    object
 1   freqCode                  745 non-null    object
 2   refPeriodId               745 non-null    int64
 3   refYear                   745 non-null    int64
 4   refMonth                  745 non-null    int64
 5   period                    745 non-null    int64
 6   reporterCode              745 non-null    int64
 7   reporterISO               745 non-null    object
 8   reporterDesc              745 non-null    object
 9   flowCode                  745 non-null    object
 10  flowDesc                  745 non-null    object
 11  partnerCode               745 non-null    int64
 12  partnerISO                745 non-null    object
 13  partnerDesc               745 non-null    object
 14  partner2Code              745 non-null    int64
 15  partner2ISO               745 non-null    object
 16  partner2Desc              745 non-null    object
 17  classificationCode        745 non-null    object
 18  classificationSearchCode  745 non-null    object
 19  isOriginalClassification  745 non-null    bool
 20  cmdCode                   745 non-null    int64
 21  cmdDesc                   745 non-null    object
 22  aggrLevel                 745 non-null    int64
 23  isLeaf                    745 non-null    bool
 24  customsCode               745 non-null    object
 25  customsDesc               745 non-null    object
 26  mosCode                   745 non-null    int64
 27  motCode                   745 non-null    int64
 28  motDesc                   745 non-null    object
 29  qtyUnitCode               745 non-null    int64
 30  qtyUnitAbbr               611 non-null    object
 31  qty                       745 non-null    float64
 32  isQtyEstimated            745 non-null    bool
 33  altQtyUnitCode            745 non-null    int64
 34  altQtyUnitAbbr            461 non-null    object
 35  altQty                    745 non-null    float64
 36  isAltQtyEstimated         745 non-null    bool
 37  netWgt                    626 non-null    float64
 38  isNetWgtEstimated         745 non-null    bool
 39  grossWgt                  745 non-null    float64
 40  isGrossWgtEstimated       745 non-null    bool
 41  cifvalue                  730 non-null    float64
 42  fobvalue                  296 non-null    float64
 43  primaryValue              745 non-null    float64
 44  legacyEstimationFlag      745 non-null    int64
 45  isReported                745 non-null    bool
 46  isAggregate               745 non-null    bool
dtypes: bool(8), float64(7), int64(14), object(18)
memory usage: 232.9+ KB

In [231]:
# unique values and there datatype for preprocessing
cols = cpo_im.columns

cpo_im_table = pd.DataFrame({
    'Column Name': cols,
    'Unique Value': [cpo_im[col].unique() for col in cols],
    'Count': [cpo_im[col].count() for col in cols],
    'Data Type': [cpo_im[col].dtypes for col in cols]
})

cpo_im_table

,Column Name,Unique Value,Count,Data Type
0,typeCode,[C],745,object
1,freqCode,[A],745,object
2,refPeriodId,"[20190101, 20200101, 20210101, 20220101, 20230...",745,int64
3,refYear,"[2019, 2020, 2021, 2022, 2023, 2024]",745,int64
4,refMonth,[52],745,int64
5,period,"[2019, 2020, 2021, 2022, 2023, 2024]",745,int64
6,reporterCode,"[4, 20, 24, 28, 31, 36, 40, 44, 48, 56, 64, 68...",745,int64
7,reporterISO,"[AFG, AND, AGO, ATG, AZE, AUS, AUT, BHS, BHR, ...",745,object
8,reporterDesc,"[Afghanistan, Andorra, Angola, Antigua and Bar...",745,object
9,flowCode,[M],745,object
10,flowDesc,[Import],745,object
11,partnerCode,[0],745,int64
12,partnerISO,[W00],745,object
13,partnerDesc,[World],745,object
14,partner2Code,[0],745,int64
15,partner2ISO,[W00],745,object
16,partner2Desc,[World],745,object
17,classificationCode,"[H4, H5, H3, H6]",745,object
18,classificationSearchCode,[HS],745,object
19,isOriginalClassification,[True],745,bool
20,cmdCode,[2709],745,int64
21,cmdDesc,[Petroleum oils and oils obtained from bitumin...,745,object
22,aggrLevel,[4],745,int64
23,isLeaf,[False],745,bool
24,customsCode,[C00],745,object
25,customsDesc,[TOTAL CPC],745,object
26,mosCode,[0],745,int64
27,motCode,[0],745,int64
28,motDesc,[TOTAL MOT],745,object
29,qtyUnitCode,"[8, -1]",745,int64
30,qtyUnitAbbr,"[kg, nan]",611,object
31,qty,"[118878782.0, 3236.85, 1804.062, 135.6, 0.0, 2...",745,float64
32,isQtyEstimated,"[False, True]",745,bool
33,altQtyUnitCode,"[8, -1, 7, 12, 21, 19, 2, 5, 20, 40]",745,int64
34,altQtyUnitAbbr,"[kg, nan, l, m³, 1000 KG, BBL, m², u, 1000 L, GT]",461,object
35,altQty,"[118878782.0, 3236.85, 1804.062, 135.6, 0.0, 2...",745,float64
36,isAltQtyEstimated,[False],745,bool
37,netWgt,"[118878782.0, 3236.85, 1804.062, 135.6, nan, 2...",626,float64
38,isNetWgtEstimated,"[False, True]",745,bool
39,grossWgt,"[0.0, 16539133500.0, 48457.79, 5270751776.0, 8...",745,float64
40,isGrossWgtEstimated,[False],745,bool
41,cifvalue,"[34372466.47, 12071.238, 17618.584, 580.737, 1...",730,float64
42,fobvalue,"[0.0, nan, 8519443877.513, 369.9, 4654709029.0...",296,float64
43,primaryValue,"[34372466.47, 12071.238, 17618.584, 580.737, 1...",745,float64
44,legacyEstimationFlag,"[0, 6, 2]",745,int64
45,isReported,[False],745,bool
46,isAggregate,[True],745,bool

In [232]:
#dropping useless columns from dataset
drop_cols_im = ['typeCode','freqCode', 'refPeriodId', 'refMonth', 'period', 
             'flowCode', 'flowDesc','partnerCode', 'partnerISO', 'partnerDesc',
             'partner2Code', 'partner2ISO', 'partner2Desc', 'classificationSearchCode',
             'isOriginalClassification', 'aggrLevel', 'isLeaf', 'customsCode', 
             'customsDesc', 'mosCode', 'motCode', 'motDesc', 'isQtyEstimated',
             'isAltQtyEstimated', 'isNetWgtEstimated', 'isGrossWgtEstimated',
             'isReported', 'isAggregate'
]

cpo_im.drop(drop_cols_im, axis=1, inplace=True)

In [233]:
# NaN value in dataset
cpo_im.isna().sum()

refYear                   0
reporterCode              0
reporterISO               0
reporterDesc              0
classificationCode        0
cmdCode                   0
cmdDesc                   0
qtyUnitCode               0
qtyUnitAbbr             134
qty                       0
altQtyUnitCode            0
altQtyUnitAbbr          284
altQty                    0
netWgt                  119
grossWgt                  0
cifvalue                 15
fobvalue                449
primaryValue              0
legacyEstimationFlag      0
dtype: int64

In [234]:
# replacing row's data from column
cpo_im['cmdDesc'] = cpo_im['cmdDesc'].replace('Petroleum oils and oils obtained from bituminous minerals; crude', 'Crude petroleum oil')

In [235]:
# removing NaN values from dataset
cpo_im['qtyUnitAbbr'] = cpo_im['qtyUnitAbbr'].fillna(cpo_im['qtyUnitAbbr'].mode()[0])
cpo_im['altQtyUnitAbbr'] = cpo_im['altQtyUnitAbbr'].fillna(cpo_im['altQtyUnitAbbr'].mode()[0])
cpo_im['netWgt'] = cpo_im['netWgt'].fillna(cpo_im['netWgt'].median())
cpo_im['cifvalue'] = cpo_im['cifvalue'].fillna(cpo_im['cifvalue'].median())
cpo_im['fobvalue'] = cpo_im['fobvalue'].fillna(cpo_im['fobvalue'].median())

In [236]:
cpo_im.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 745 entries, 0 to 744
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   refYear               745 non-null    int64
 1   reporterCode          745 non-null    int64
 2   reporterISO           745 non-null    object
 3   reporterDesc          745 non-null    object
 4   classificationCode    745 non-null    object
 5   cmdCode               745 non-null    int64
 6   cmdDesc               745 non-null    object
 7   qtyUnitCode           745 non-null    int64
 8   qtyUnitAbbr           745 non-null    object
 9   qty                   745 non-null    float64
 10  altQtyUnitCode        745 non-null    int64
 11  altQtyUnitAbbr        745 non-null    object
 12  altQty                745 non-null    float64
 13  netWgt                745 non-null    float64
 14  grossWgt              745 non-null    float64
 15  cifvalue              745 non-null    float64
 16  fobvalue              745 non-null    float64
 17  primaryValue          745 non-null    float64
 18  legacyEstimationFlag  745 non-null    int64
dtypes: float64(7), int64(6), object(6)
memory usage: 110.7+ KB

In [237]:
cols = cpo_im.columns

cpo_im_table = pd.DataFrame({
    'Column Name': cols,
    'Unique Value': [cpo_im[col].unique() for col in cols],
    'Count': [cpo_im[col].count() for col in cols],
    'Data Type': [cpo_im[col].dtypes for col in cols]
})

cpo_im_table

,Column Name,Unique Value,Count,Data Type
0,refYear,"[2019, 2020, 2021, 2022, 2023, 2024]",745,int64
1,reporterCode,"[4, 20, 24, 28, 31, 36, 40, 44, 48, 56, 64, 68...",745,int64
2,reporterISO,"[AFG, AND, AGO, ATG, AZE, AUS, AUT, BHS, BHR, ...",745,object
3,reporterDesc,"[Afghanistan, Andorra, Angola, Antigua and Bar...",745,object
4,classificationCode,"[H4, H5, H3, H6]",745,object
5,cmdCode,[2709],745,int64
6,cmdDesc,[Crude petroleum oil],745,object
7,qtyUnitCode,"[8, -1]",745,int64
8,qtyUnitAbbr,[kg],745,object
9,qty,"[118878782.0, 3236.85, 1804.062, 135.6, 0.0, 2...",745,float64
10,altQtyUnitCode,"[8, -1, 7, 12, 21, 19, 2, 5, 20, 40]",745,int64
11,altQtyUnitAbbr,"[kg, l, m³, 1000 KG, BBL, m², u, 1000 L, GT]",745,object
12,altQty,"[118878782.0, 3236.85, 1804.062, 135.6, 0.0, 2...",745,float64
13,netWgt,"[118878782.0, 3236.85, 1804.062, 135.6, 683203...",745,float64
14,grossWgt,"[0.0, 16539133500.0, 48457.79, 5270751776.0, 8...",745,float64
15,cifvalue,"[34372466.47, 12071.238, 17618.584, 580.737, 1...",745,float64
16,fobvalue,"[0.0, 8519443877.513, 369.9, 4654709029.0, 142...",745,float64
17,primaryValue,"[34372466.47, 12071.238, 17618.584, 580.737, 1...",745,float64
18,legacyEstimationFlag,"[0, 6, 2]",745,int64

In [265]:
# Saving Crude petroleum oil import

interim_path = r'../data/interim/crude_pertroleum_import.csv'

cpo_im.to_csv(interim_path, index=False)

### Export

In [250]:
# chekcing type of encoding we have in our csv dataset
import chardet


filepath = r'Raw\crude petroleum oils\Crude oil export\TradeData_12_11_2025_20_25_51.csv'
with open(filepath, 'rb') as f:
    result = chardet.detect(f.read(200000))

print(result)

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

In [251]:
#loading export data
cpo_ex = pd.read_excel(r'Raw\crude petroleum oils\Crude oil export\TradeData.xlsx')
cpo_ex.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20240101,2024,52,2024,24,AGO,Angola,X,...,3.917605e+08,False,0.000000e+00,False,NaN,3.125730e+10,3.125730e+10,0,False,True
1,C,A,20240101,2024,52,2024,31,AZE,Azerbaijan,X,...,2.359617e+10,False,0.000000e+00,False,NaN,1.443736e+10,1.443736e+10,0,False,True
2,C,A,20240101,2024,52,2024,32,ARG,Argentina,X,...,8.686507e+09,False,0.000000e+00,False,NaN,4.931109e+09,4.931109e+09,0,False,True
3,C,A,20240101,2024,52,2024,36,AUS,Australia,X,...,NaN,False,1.106208e+07,False,NaN,7.064712e+09,7.064712e+09,0,False,True
4,C,A,20240101,2024,52,2024,52,BRB,Barbados,X,...,2.423800e+07,False,0.000000e+00,False,NaN,1.363348e+07,1.363348e+07,0,False,True

In [252]:
#shape of the dataset
cpo_ex.shape

(75, 47)

In [ ]:
#information about export dataset
cpo_ex.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   typeCode                  75 non-null     object
 1   freqCode                  75 non-null     object
 2   refPeriodId               75 non-null     int64
 3   refYear                   75 non-null     int64
 4   refMonth                  75 non-null     int64
 5   period                    75 non-null     int64
 6   reporterCode              75 non-null     int64
 7   reporterISO               75 non-null     object
 8   reporterDesc              75 non-null     object
 9   flowCode                  75 non-null     object
 10  flowDesc                  75 non-null     object
 11  partnerCode               75 non-null     int64
 12  partnerISO                75 non-null     object
 13  partnerDesc               75 non-null     object
 14  partner2Code              75 non-null     int64
 15  partner2ISO               75 non-null     object
 16  partner2Desc              75 non-null     object
 17  classificationCode        75 non-null     object
 18  classificationSearchCode  75 non-null     object
 19  isOriginalClassification  75 non-null     bool
 20  cmdCode                   75 non-null     int64
 21  cmdDesc                   75 non-null     object
 22  aggrLevel                 75 non-null     int64
 23  isLeaf                    75 non-null     bool
 24  customsCode               75 non-null     object
 25  customsDesc               75 non-null     object
 26  mosCode                   75 non-null     int64
 27  motCode                   75 non-null     int64
 28  motDesc                   75 non-null     object
 29  qtyUnitCode               75 non-null     int64
 30  qtyUnitAbbr               66 non-null     object
 31  qty                       75 non-null     float64
 32  isQtyEstimated            75 non-null     bool
 33  altQtyUnitCode            75 non-null     int64
 34  altQtyUnitAbbr            51 non-null     object
 35  altQty                    75 non-null     float64
 36  isAltQtyEstimated         75 non-null     bool
 37  netWgt                    65 non-null     float64
 38  isNetWgtEstimated         75 non-null     bool
 39  grossWgt                  75 non-null     float64
 40  isGrossWgtEstimated       75 non-null     bool
 41  cifvalue                  1 non-null      float64
 42  fobvalue                  75 non-null     float64
 43  primaryValue              75 non-null     float64
 44  legacyEstimationFlag      75 non-null     int64
 45  isReported                75 non-null     bool
 46  isAggregate               75 non-null     bool
dtypes: bool(8), float64(7), int64(14), object(18)
memory usage: 23.6+ KB

In [254]:
# unique value each colume have in the dataset to observe and remove unnecessary columns from dataset

cols = [
       'freqCode', 'refPeriodId', 'refMonth','typeCode', 'refYear', 'period', 'reporterCode', 
       'reporterISO', 'reporterDesc', 'flowCode', 'flowDesc',
       'partnerCode', 'partnerISO', 'partnerDesc', 'partner2Code',
       'partner2ISO', 'partner2Desc', 'classificationCode',
       'classificationSearchCode', 'isOriginalClassification', 'cmdCode',
       'cmdDesc', 'aggrLevel', 'isLeaf', 'customsCode', 'customsDesc',
       'mosCode', 'motCode', 'motDesc', 'qtyUnitCode', 'qtyUnitAbbr', 'qty',
       'isQtyEstimated', 'altQtyUnitCode', 'altQtyUnitAbbr', 'altQty',
       'isAltQtyEstimated', 'netWgt', 'isNetWgtEstimated', 'grossWgt',
       'isGrossWgtEstimated', 'cifvalue', 'fobvalue', 'primaryValue',
       'legacyEstimationFlag', 'isReported', 'isAggregate'
]

unique_table = pd.DataFrame({
    "column_name": cols,
    "unique_values": [cpo_ex[col].dropna().unique().tolist() for col in cols],
    "unique_count": [cpo_ex[col].nunique() for col in cols],
    'dtype': [cpo_ex[col].dtypes for col in cols]
})

unique_table

,column_name,unique_values,unique_count,dtype
0,freqCode,[A],1,object
1,refPeriodId,[20240101],1,int64
2,refMonth,[52],1,int64
3,typeCode,[C],1,object
4,refYear,[2024],1,int64
5,period,[2024],1,int64
6,reporterCode,"[24, 31, 32, 36, 52, 56, 68, 70, 76, 96, 124, ...",75,int64
7,reporterISO,"[AGO, AZE, ARG, AUS, BRB, BEL, BOL, BIH, BRA, ...",75,object
8,reporterDesc,"[Angola, Azerbaijan, Argentina, Australia, Bar...",75,object
9,flowCode,[X],1,object
10,flowDesc,[Export],1,object
11,partnerCode,[0],1,int64
12,partnerISO,[W00],1,object
13,partnerDesc,[World],1,object
14,partner2Code,[0],1,int64
15,partner2ISO,[W00],1,object
16,partner2Desc,[World],1,object
17,classificationCode,"[H6, H5, H4]",3,object
18,classificationSearchCode,[HS],1,object
19,isOriginalClassification,[True],1,bool
20,cmdCode,[2709],1,int64
21,cmdDesc,[Petroleum oils and oils obtained from bitumin...,1,object
22,aggrLevel,[4],1,int64
23,isLeaf,[False],1,bool
24,customsCode,[C00],1,object
25,customsDesc,[TOTAL CPC],1,object
26,mosCode,[0],1,int64
27,motCode,[0],1,int64
28,motDesc,[TOTAL MOT],1,object
29,qtyUnitCode,"[8, -1]",2,int64
30,qtyUnitAbbr,[kg],1,object
31,qty,"[391760460.0, 23596170696.0, 8686507120.0, 137...",66,float64
32,isQtyEstimated,"[False, True]",2,bool
33,altQtyUnitCode,"[8, 7, -1, 19, 12, 5, 21]",7,int64
34,altQtyUnitAbbr,"[kg, l, BBL, m³, u, 1000 KG]",6,object
35,altQty,"[391760460.0, 23596170696.0, 8686507120.0, 137...",51,float64
36,isAltQtyEstimated,[False],1,bool
37,netWgt,"[391760460.0, 23596170696.0, 8686507120.0, 242...",64,float64
38,isNetWgtEstimated,"[False, True]",2,bool
39,grossWgt,"[0.0, 11062078.974, 3036654.0, 725303735.0, 28...",5,float64
40,isGrossWgtEstimated,[False],1,bool
41,cifvalue,[21881.578],1,float64
42,fobvalue,"[31257304278.03, 14437355994.08, 4931109474.66...",75,float64
43,primaryValue,"[31257304278.03, 14437355994.08, 4931109474.66...",75,float64
44,legacyEstimationFlag,"[0, 6]",2,int64
45,isReported,[False],1,bool
46,isAggregate,[True],1,bool

In [255]:
cpo_ex['cmdDesc'] = cpo_ex['cmdDesc'].replace('Petroleum oils and oils obtained from bituminous minerals; crude', 'Crude petroleum oil')

In [256]:
# list of columns that get removed from export dataset
drop_cols_ex = ['typeCode','freqCode', 'refPeriodId', 'refMonth', 'period', 
             'flowCode', 'flowDesc','partnerCode', 'partnerISO', 'partnerDesc',
             'partner2Code', 'partner2ISO', 'partner2Desc', 'classificationSearchCode',
             'isOriginalClassification', 'aggrLevel', 'isLeaf', 'customsCode', 
             'customsDesc', 'mosCode', 'motCode', 'motDesc', 'isQtyEstimated',
             'isAltQtyEstimated', 'isNetWgtEstimated', 'isGrossWgtEstimated',
             'isReported', 'isAggregate'
]

cpo_ex.drop(drop_cols_ex, axis=1, inplace=True)

In [257]:
cpo_ex.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   refYear               75 non-null     int64
 1   reporterCode          75 non-null     int64
 2   reporterISO           75 non-null     object
 3   reporterDesc          75 non-null     object
 4   classificationCode    75 non-null     object
 5   cmdCode               75 non-null     int64
 6   cmdDesc               75 non-null     object
 7   qtyUnitCode           75 non-null     int64
 8   qtyUnitAbbr           66 non-null     object
 9   qty                   75 non-null     float64
 10  altQtyUnitCode        75 non-null     int64
 11  altQtyUnitAbbr        51 non-null     object
 12  altQty                75 non-null     float64
 13  netWgt                65 non-null     float64
 14  grossWgt              75 non-null     float64
 15  cifvalue              1 non-null      float64
 16  fobvalue              75 non-null     float64
 17  primaryValue          75 non-null     float64
 18  legacyEstimationFlag  75 non-null     int64
dtypes: float64(7), int64(6), object(6)
memory usage: 11.3+ KB

In [258]:
# column with NaN values
cpo_ex.isna().sum()

refYear                  0
reporterCode             0
reporterISO              0
reporterDesc             0
classificationCode       0
cmdCode                  0
cmdDesc                  0
qtyUnitCode              0
qtyUnitAbbr              9
qty                      0
altQtyUnitCode           0
altQtyUnitAbbr          24
altQty                   0
netWgt                  10
grossWgt                 0
cifvalue                74
fobvalue                 0
primaryValue             0
legacyEstimationFlag     0
dtype: int64

In [259]:
# checking for NaN values and replacing with mode() into the object column
print('Number of values available in the altQtyUnitAbbr is - \n\n',cpo_ex['altQtyUnitAbbr'].unique())
cpo_ex['altQtyUnitAbbr'] = cpo_ex['altQtyUnitAbbr'].fillna(cpo_ex['altQtyUnitAbbr'].mode()[0])

Number of values available in the altQtyUnitAbbr is -

 ['kg' 'l' nan 'BBL' 'm³' 'u' '1000 KG']

In [260]:
# Filling NaN values in Numerical columns
cpo_ex['netWgt'] = cpo_ex['netWgt'].fillna(cpo_ex['netWgt'].median())
cpo_ex['cifvalue'] = cpo_ex['cifvalue'].fillna(cpo_ex['cifvalue'].mode()[0])

In [261]:
# Saving Crude petroleum oil

interim_path = r'../data/interim/crude_pertroleum_export.csv'

cpo_ex.to_csv(interim_path, index=False)