In [234]:
import pandas as pd
import numpy as np
import os
import sys

In [235]:
BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), '..'))
data_path = os.path.join(BASE_DIR, 'data', 'raw', 'Price & Micro time series')
print(data_path)

c:\Users\Atul Goswami\Desktop\Dataset\Data-Science-Project\data\raw\Price & Micro time series

## Price And Micro Time Series
- 1 Bitcoin Etherium
- 2 Brent Crude Price and WTI
- 3 Interest Rate
- 4 USD Index

## 1 Bitcoin Etherium

In [236]:
bitcoin_path = os.path.join(data_path, 'BITCOIN ETHERIUS', 'btc-usd-max.csv')

be = pd.read_csv(bitcoin_path)

be.head()

                snapped_at   price    market_cap  total_volume
0  2013-04-28 00:00:00 UTC  135.30  1.500518e+09           0.0
1  2013-04-29 00:00:00 UTC  141.96  1.575032e+09           0.0
2  2013-04-30 00:00:00 UTC  135.30  1.501657e+09           0.0
3  2013-05-01 00:00:00 UTC  117.00  1.298952e+09           0.0
4  2013-05-02 00:00:00 UTC  103.43  1.148668e+09           0.0

In [237]:
be.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4609 entries, 0 to 4608
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   snapped_at    4609 non-null   object
 1   price         4609 non-null   float64
 2   market_cap    4609 non-null   float64
 3   total_volume  4609 non-null   float64
dtypes: float64(3), object(1)
memory usage: 144.2+ KB

In [238]:
be.describe()

               price    market_cap  total_volume
count    4609.000000  4.609000e+03  4.609000e+03
mean    23676.738007  4.568970e+11  1.843528e+10
std     30757.729628  6.094069e+11  2.189811e+10
min        67.809000  7.713681e+08  0.000000e+00
25%       654.518638  9.781273e+09  5.415581e+08
50%      8902.568995  1.587223e+11  1.203330e+10
75%     37287.391402  7.052927e+11  2.961126e+10
max    124773.508231  2.486073e+12  1.904603e+11

In [239]:
be.isna().sum()

snapped_at      0
price           0
market_cap      0
total_volume    0
dtype: int64

In [240]:
be['snapped_at'] = pd.to_datetime(be['snapped_at'])

In [241]:
be.head()

                 snapped_at   price    market_cap  total_volume
0 2013-04-28 00:00:00+00:00  135.30  1.500518e+09           0.0
1 2013-04-29 00:00:00+00:00  141.96  1.575032e+09           0.0
2 2013-04-30 00:00:00+00:00  135.30  1.501657e+09           0.0
3 2013-05-01 00:00:00+00:00  117.00  1.298952e+09           0.0
4 2013-05-02 00:00:00+00:00  103.43  1.148668e+09           0.0

In [242]:
be.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4609 entries, 0 to 4608
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   snapped_at    4609 non-null   datetime64[ns, UTC]
 1   price         4609 non-null   float64
 2   market_cap    4609 non-null   float64
 3   total_volume  4609 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(3)
memory usage: 144.2 KB

In [243]:
be.describe()

               price    market_cap  total_volume
count    4609.000000  4.609000e+03  4.609000e+03
mean    23676.738007  4.568970e+11  1.843528e+10
std     30757.729628  6.094069e+11  2.189811e+10
min        67.809000  7.713681e+08  0.000000e+00
25%       654.518638  9.781273e+09  5.415581e+08
50%      8902.568995  1.587223e+11  1.203330e+10
75%     37287.391402  7.052927e+11  2.961126e+10
max    124773.508231  2.486073e+12  1.904603e+11

In [244]:
## storing cleaned data in processed folder
save_path = os.path.join(BASE_DIR, 'data', 'processed')

final_bitcoin = os.path.join(save_path, 'Micro Time Series', 'Bitcoin Etherium', 'bitcoin_etherium.csv')

be.to_csv(final_bitcoin, index=False)

## 2 Brent Crude Price and WTI

In [245]:
brent_path = os.path.join(data_path,'BRENT CRUDE PRICE AND WTI', 'WTIBrentSpread2.csv')

brent = pd.read_csv(brent_path)

brent.head()

       Date    WTI  Brent  Spread
0  1/3/2006  63.11  61.51    1.60
1  1/4/2006  63.41  61.25    2.16
2  1/5/2006  62.81  61.68    1.13
3  1/6/2006  64.21  62.43    1.78
4  1/9/2006  63.56  62.51    1.05

In [246]:
brent.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1303 non-null   object
 1   WTI     1303 non-null   float64
 2   Brent   1303 non-null   float64
 3   Spread  1303 non-null   float64
dtypes: float64(3), object(1)
memory usage: 40.8+ KB

In [247]:
brent['Date'] = pd.to_datetime(brent['Date'])

In [248]:
brent.describe()

                                Date          WTI        Brent       Spread
count                           1303  1303.000000  1303.000000  1303.000000
mean   2008-07-26 02:02:40.245587200    76.226531    75.846462     0.380069
min              2006-01-03 00:00:00    30.280000    33.730000   -19.460000
25%              2007-04-11 12:00:00    63.250000    62.920000    -1.215000
50%              2008-07-25 00:00:00    73.120000    73.080000     0.860000
75%              2009-11-07 12:00:00    84.420000    84.710000     2.330000
max              2011-02-23 00:00:00   145.310000   143.950000    22.180000
std                              NaN    20.312852    19.972919     3.397434

In [249]:
# saving cleaned dataset

final_brent = os.path.join(save_path, 'Micro Time Series', 'Brent Crude Price and WTI', 'brent_crude_wti.csv')

brent.to_csv(final_brent, index=False)

## 3 Interest Rate

In [250]:
# loading dataset
interest_path = os.path.join(data_path, 'INTEREST RATE', 'FEDFUNDS.csv')

ir = pd.read_csv(interest_path)

ir.head()

  observation_date  FEDFUNDS
0       2024-11-01      4.64
1       2024-12-01      4.48
2       2025-01-01      4.33
3       2025-02-01      4.33
4       2025-03-01      4.33

In [251]:
ir.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  13 non-null     object
 1   FEDFUNDS          13 non-null     float64
dtypes: float64(1), object(1)
memory usage: 340.0+ bytes

In [252]:
ir['observation_date'] = pd.to_datetime(ir['observation_date'])

In [253]:
ir.describe()

                    observation_date   FEDFUNDS
count                             13  13.000000
mean   2025-05-01 22:09:13.846153728   4.303846
min              2024-11-01 00:00:00   3.880000
25%              2025-02-01 00:00:00   4.330000
50%              2025-05-01 00:00:00   4.330000
75%              2025-08-01 00:00:00   4.330000
max              2025-11-01 00:00:00   4.640000
std                              NaN   0.178397

In [254]:
# Saving intrest dataset
final_interest = os.path.join(save_path, 'Micro Time Series', 'Interest Rate', 'interest_rate.csv')

ir.to_csv(final_interest, index=False)

## 4 USD Index

In [255]:
usd_path = os.path.join(data_path, 'USD INDEX', 'DTWEXBGS.csv')

usd = pd.read_csv(usd_path)

usd.head()

  observation_date  DTWEXBGS
0       2024-12-05  126.6638
1       2024-12-06  126.9271
2       2024-12-09  126.8394
3       2024-12-10  127.1884
4       2024-12-11  127.0950

In [256]:
usd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  262 non-null    object
 1   DTWEXBGS          251 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.2+ KB

In [257]:
usd['observation_date'] = pd.to_datetime(usd['observation_date'])

In [258]:
# Checking for NaN values
usd.isna().sum()

observation_date     0
DTWEXBGS            11
dtype: int64

In [259]:
usd.head()

  observation_date  DTWEXBGS
0       2024-12-05  126.6638
1       2024-12-06  126.9271
2       2024-12-09  126.8394
3       2024-12-10  127.1884
4       2024-12-11  127.0950

In [260]:
usd.describe()

                    observation_date    DTWEXBGS
count                            262  251.000000
mean   2025-06-06 02:17:24.274809088  123.593485
min              2024-12-05 00:00:00  119.586000
25%              2025-03-06 06:00:00  120.977750
50%              2025-06-05 12:00:00  122.073500
75%              2025-09-04 18:00:00  126.791750
max              2025-12-05 00:00:00  130.214200
std                              NaN    3.211132

In [261]:
usd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  262 non-null    datetime64[ns]
 1   DTWEXBGS          251 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.2 KB

In [262]:
# Saving Dataset 
final_usd = os.path.join(save_path, 'Micro Time Series', 'Usd Index', 'usd_index.csv')
usd.to_csv(final_usd, index=False)