In [1]:
import pandas as pd
import numpy as np

path = "US Dollar Index Historical Data.csv"  
df = pd.read_csv(path)

print(df.shape)
df.head()

(660, 7)

         Date  Price   Open    High    Low   Vol. Change %
0  01/01/2026  98.92  98.23   98.99  98.15    NaN    0.61%
1  12/01/2025  98.32  99.48   99.57  97.75  0.00K   -1.13%
2  11/01/2025  99.44  99.75  100.39  98.99    NaN   -0.36%
3  10/01/2025  99.80  97.82   99.84  97.46    NaN    2.08%
4  09/01/2025  97.78  97.83   98.64  96.22  0.00K    0.00%

In [2]:
df.info()
df.isna().mean().sort_values(ascending=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660 entries, 0 to 659
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      660 non-null    object
 1   Price     660 non-null    float64
 2   Open      660 non-null    float64
 3   High      660 non-null    float64
 4   Low       660 non-null    float64
 5   Vol.      9 non-null      object
 6   Change %  660 non-null    object
dtypes: float64(4), object(3)
memory usage: 36.2+ KB

Vol.        0.986364
Price       0.000000
Date        0.000000
Open        0.000000
High        0.000000
Low         0.000000
Change %    0.000000
dtype: float64

In [3]:
df["Date"] = pd.to_datetime(df["Date"], format="%m/%d/%Y", errors="raise")

df["Date"] = df["Date"].dt.to_period("M").dt.to_timestamp()  # YYYY-MM-01

df = df.sort_values("Date").reset_index(drop=True)

df[["Date"]].head(), df[["Date"]].tail()

(        Date
 0 1971-02-01
 1 1971-03-01
 2 1971-04-01
 3 1971-05-01
 4 1971-06-01,
           Date
 655 2025-09-01
 656 2025-10-01
 657 2025-11-01
 658 2025-12-01
 659 2026-01-01)

In [5]:
df["Change %"] = (
    df["Change %"]
    .astype(str)
    .str.replace("%", "", regex=False)
    .str.replace(",", ".", regex=False)
)

df["Change %"] = pd.to_numeric(df["Change %"], errors="coerce")

df["Change %"].describe()

count    660.000000
mean      -0.000439
std        2.422739
min       -8.150000
25%       -1.490000
50%       -0.030000
75%        1.517500
max        9.440000
Name: Change %, dtype: float64

In [6]:
df = df.drop(columns=["Vol."])
df.head()

        Date   Price    Open    High     Low  Change %
0 1971-02-01  120.26  120.26  120.29  120.12      0.02
1 1971-03-01  120.17  120.25  120.25  120.13     -0.07
2 1971-04-01  120.19  120.18  120.31  120.16      0.02
3 1971-05-01  119.43  120.17  120.17  118.91     -0.63
4 1971-06-01  119.16  119.69  119.69  119.16     -0.23

In [9]:
num_cols = [c for c in df.columns if c != "Date"]
for c in num_cols:
    df[c] = pd.to_numeric(df[c], errors="coerce")

# Basit tutarlılık kontrolü
bad = df[(df["High"] < df["Low"]) | (df["High"] < df["Price"]) | (df["Low"] > df["Price"])]
print("# of inconsistent row:", len(bad))

# Date unique mi?
print("# of Duplicate date:", df["Date"].duplicated().sum())

# Kaydet
df.to_csv("US_Dollar_Index_cleaned.csv", index=False)
df.tail()

# of inconsistent row: 0
# of Duplicate date: 0

          Date  Price   Open    High    Low  Change %
655 2025-09-01  97.78  97.83   98.64  96.22      0.00
656 2025-10-01  99.80  97.82   99.84  97.46      2.08
657 2025-11-01  99.44  99.75  100.39  98.99     -0.36
658 2025-12-01  98.32  99.48   99.57  97.75     -1.13
659 2026-01-01  98.92  98.23   98.99  98.15      0.61